2024-07-13 23:03:37,801 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-07-13 23:03:37,801 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Configure stats pid to 7428
2024-07-13 23:03:37,801 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Loading settings from C:\Users\fangy\.config\wandb\settings
2024-07-13 23:03:37,801 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Loading settings from d:\Github\DeepShadow\yolov5\wandb\settings
2024-07-13 23:03:37,801 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-13 23:03:37,801 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': 'd:\\Github\\DeepShadow\\yolov5\\train.py', 'program': 'd:\\Github\\DeepShadow\\yolov5\\train.py'}
2024-07-13 23:03:37,801 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Applying login settings: {'login_timeout': 30}
2024-07-13 23:03:37,802 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-13 23:03:37,802 INFO    MainThread:7428 [wandb_init.py:_log_setup():521] Logging user logs to D:\Github\DeepShadow\yolov5\wandb\run-20240713_230337-q1mfuwim\logs\debug.log
2024-07-13 23:03:37,802 INFO    MainThread:7428 [wandb_init.py:_log_setup():522] Logging internal logs to D:\Github\DeepShadow\yolov5\wandb\run-20240713_230337-q1mfuwim\logs\debug-internal.log
2024-07-13 23:03:37,802 INFO    MainThread:7428 [wandb_init.py:init():561] calling init triggers
2024-07-13 23:03:37,802 INFO    MainThread:7428 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'weights': 'yolov5s.pt', 'cfg': '', 'data': '../tele_datasets/mixed\\data.yaml', 'hyp': {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}, 'epochs': 300, 'batch_size': 2, 'imgsz': 1024, 'rect': False, 'resume': False, 'nosave': False, 'noval': False, 'noautoanchor': False, 'noplots': False, 'evolve': None, 'evolve_population': WindowsPath('data/hyps'), 'resume_evolve': None, 'bucket': '', 'cache': 'ram', 'image_weights': False, 'device': '', 'multi_scale': False, 'single_cls': False, 'optimizer': 'SGD', 'sync_bn': False, 'workers': 8, 'project': 'runs\\train', 'name': 'results_1', 'exist_ok': False, 'quad': False, 'cos_lr': False, 'label_smoothing': 0.0, 'patience': 100, 'freeze': [0], 'save_period': -1, 'seed': 0, 'local_rank': -1, 'entity': None, 'upload_dataset': False, 'bbox_interval': -1, 'artifact_alias': 'latest', 'ndjson_console': False, 'ndjson_file': False, 'save_dir': 'runs\\train\\results_1'}
2024-07-13 23:03:37,802 INFO    MainThread:7428 [wandb_init.py:init():611] starting backend
2024-07-13 23:03:37,802 INFO    MainThread:7428 [wandb_init.py:init():615] setting up manager
2024-07-13 23:03:37,804 INFO    MainThread:7428 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-07-13 23:03:37,806 INFO    MainThread:7428 [wandb_init.py:init():623] backend started and connected
2024-07-13 23:03:37,808 INFO    MainThread:7428 [wandb_init.py:init():715] updated telemetry
2024-07-13 23:03:37,830 INFO    MainThread:7428 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-07-13 23:03:45,798 INFO    Thread-9  :7428 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\urllib3\connectionpool.py", line 712, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\urllib3\connectionpool.py", line 1014, in _prepare_proxy
    conn.connect()
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\fangy\miniconda3\envs\normal\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\fangy\miniconda3\envs\normal\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "C:\Users\fangy\miniconda3\envs\normal\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\urllib3\connectionpool.py", line 801, in urlopen
    retries = retries.increment(
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\urllib3\util\retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\fangy\miniconda3\envs\normal\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2024-07-13 23:04:27,249 INFO    MainThread:7428 [wandb_run.py:_on_init():2357] communicating current version
2024-07-13 23:04:31,140 INFO    MainThread:7428 [wandb_run.py:_on_init():2366] got version response upgrade_message: "wandb version 0.17.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-07-13 23:04:31,143 INFO    MainThread:7428 [wandb_init.py:init():799] starting run threads in backend
2024-07-13 23:04:35,606 INFO    MainThread:7428 [wandb_run.py:_console_start():2335] atexit reg
2024-07-13 23:04:35,606 INFO    MainThread:7428 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-07-13 23:04:35,606 INFO    MainThread:7428 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-07-13 23:04:35,606 INFO    MainThread:7428 [wandb_run.py:_redirect():2280] Redirects installed.
2024-07-13 23:04:35,606 INFO    MainThread:7428 [wandb_init.py:init():842] run started, returning control to user process
